### ISSUE TITLE
Memory usage RBioformats vs FIJI/bioformats

### ISSUE THREAD

**Issue by graukatze** [aoles/RBioFormats#18]
Hi, Andrzej!

I have a new issue and I am not sure if it occurred because of a more recent version of bioformats. In short, opening the same file on ImageJ/Fiji (bioformats 6.1) uses 2.12GB of RAM, while read.image in R occupies 22.73GB (bioformats 6.0.0)! Is there a way to go back to an earlier version of RBioFormats to see if this a new issue?

Many thanks,
Geo

**Comment by aoles** [comment]
Hi,
interesting, might be the case that ImageJ/Fiji does not actually load the whole image stack into memory like RBioFormats does but rather take a subset e.g. a lower resolution preview. How big is the file on disk?

Considering the recent fix, probably the easiest way for you to get a working copy with an earlier version of bioformats library would be to clone the repo, switch to the `debug` branch and edit the field in DESCRIPTION file to use a different version of the library, like so:

```sh
git clone https://github.com/aoles/RBioFormats.git
cd RBioFormats
git checkout
# edit DESCRITPION to change `BioFormats: 6.0.0` to e.g. `BioFormats: 5.9.0`
R CMD INSTALL .
```

**Comment by graukatze** [comment]
I guess I need to clarify - the R object has the expected size (3.4Gb) but the rsession gets huge (>20Gb). After running
```
gc()

memory is down from 22Gb to 6-7Gb. Could be related to rJava.

**Comment by graukatze** [comment]
With a fresh installation, upgraded from R 3.5.3 to R 3.6.0 memory use is now maxing out at 8-9GB.

**Comment by aoles** [comment]
Thanks for looking into this! So do you still think that there is a problem? It would be great if it would be possible for you to share a sample file illustrating the issue, then I could follow up on this properly.

Have a nice weekend,
Andrzej

**Comment by graukatze** [comment]
Hi, Andrzej!

Something is off here (R 3.6.0 didn't help - still occupying huge RAM, and hence using swap space which makes the process extremely slow).

A sample file is here: https://www.dropbox.com/s/dbzo9nythcv0iun/Test_01_99wf_Camera_Git.cxd?dl=0

The code I am running is the following:
```
options(java.parameters = "-Xmx11g" )
library(EBImage)
library(RBioFormats)

 img2 <- read.image("Test_01_99wf_Camera_Git.cxd")
```

Can you please check this? I don't remember this to be an issue before, but I also can't find an older version of RBioFormats that does not have the issue.

Many thanks,
Geo

**Comment by graukatze** [comment]
The culprit lies in the default parameters of read.image:

`read.image(file, filter.metadata = FALSE, proprietary.metadata = TRUE,
  normalize = TRUE, series, resolution, subset, read.metadata = TRUE)`

versus

`img2 <- read.image(file, read.metadata = FALSE, normalize = FALSE)
`
The normalization step makes a huge difference - turning this off (and to some extend also ignoring metadata) fixes the issue. I would almost suggest to make normalize=FALSE the default.
