### ISSUE TITLE
RBioFormats not working offline

### ISSUE THREAD

**Issue by jkh1** [aoles/RBioFormats#31]
It looks like each time RBioFormats is called, it's downloading bioformats_package.jar from openmicroscopy.org.
This shouldn't be necessary after installation since the file should have already been downloaded at installation time. 
Importantly this prevents using it in any offline application.
This is maybe a regression from #23.

**Comment by aoles** [comment]
Thanks @jkh1 for reporting this! Of course, bioformats_package.jar library should be downloaded only once during package installation, and no internet connection should be necessary later on when loading the package. I will look into fixing this.
