### ISSUE TITLE
`RBioFormats::coreMetadata(x)` does not work but `coreMetadata(x)` does

### ISSUE THREAD

**Issue by lambdamoses** [aoles/RBioFormats#37]
Basically,

```
meta <- RBioFormats::read.metadata(file)
core <- RBioFormats::coreMetadata(meta)
```

will throw this mysterious error: `Error in x[[type]] : no such index at level 1`

I think the culprit is this line: https://github.com/aoles/RBioFormats/blob/5ec5fad9a5b5ccccc62af638e3c2019f51659816/R/metadataAccessors.R#L35

When I call `coreMetadata(meta)`, `type` has length 1 and will be `coreMetadata`. However, when I call `RBioFormats::coreMetadata(meta)`, `type` has length 3: `c("RBioFormats", "::", "coreMetadata")`, so this line will not work, leading to the error above: https://github.com/aoles/RBioFormats/blob/5ec5fad9a5b5ccccc62af638e3c2019f51659816/R/metadataAccessors.R#L44

This matters because I have to call `RBioFormats::coreMetadata(meta)` within a package when `RBioFormats` is in Suggests but not Imports. I'm not sure if I should import it because it's not used for core functionalities of my package and the Java config and `BioFormats` download the first time loading `RBioFormats` will make my package more difficult to install, but because of this problem here I have to import `RBioFormats`.

**Comment by lambdamoses** [comment]
Anyway, for the package, I found a workaround to not to import `RBioFormats`:

```
coreMetadata <- RBioFormats::coreMetadata
coreMetadata(meta)
```

But still, it's really surprising that `RBioFormats::coreMetadata(meta)` doesn't work.

**Comment by aoles** [comment]
Hi,

thanks a lot for reporting this issue! Let me apologize for not getting back to you earlier, I've been away on a skiing holiday ;) 

I appreciate the detailed description and analysis of the problem you've encountered. In fact, the implementation of metadata accessors is kind of hacky and could be indeed improved. I will look into fixing this such that calls via `RBioFormats::*` work as expected.

Last but not least, it's great to hear that you find RBioFormats useful in your project. May I ask, what is the package of yours you are working on?

Cheers!

**Comment by lambdamoses** [comment]
The package of interest is `SpatialFeatureExperiment`, which is already on Bioconductor. I use `RBioFormats` to read the OME-TIFF images from Xenium, and that's for the next release.
