### ISSUE TITLE
Null pointer exception the first time calling RBioFormats function

### ISSUE THREAD

**Issue by lambdamoses** [aoles/RBioFormats#42]
The first time I call a RBioFormats function in a fresh R session, I get errors like this:

```r
> library(RBioFormats)
> try(m <- read.omexml(file.path(fn, "morphology_focus.ome.tif")))
Error in .jcall(.jcall("RBioFormats", "Lloci/formats/meta/MetadataStore;",  : 
  java.lang.NullPointerException: Cannot invoke "loci.formats.DimensionSwapper.setMetadataFiltered(boolean)" because "RBioFormats.reader" is null
```

But the second time things work fine. So in my package which suggests RBioFormats, I wrap the first call in `try` before doing the actual thing in examples and unit tests, which is a bit annoying and confusing to users. I'm on Mac. Why does this happen?

**Comment by aoles** [comment]
Thanks for reporting this phenomenon and let me apologize for the inconvenience.  I'm getting the same error as you, seems to be a bug. I will address it ASAP, so stay tuned. Cheers!

**Comment by cathalgking** [comment]
@aoles has this update been pushed to Biocmanager? I am using `RBioFormats` version 1.4.0 and get this error when trying to knit my R markdown file in RStudio.

**Comment by cathalgking** [comment]
Hi @aoles 
Just following up on this again. I still get this issue and am running 
```{r}
> packageVersion("RBioFormats")
[1] ‘1.4.0’
```

Is there any workaround that you can suggest?

**Comment by lambdamoses** [comment]
I no longer get it in 1.6.0

**Comment by aoles** [comment]
Hi @cathalgking 

Thanks for reaching out. The fix has been included on Bioconductor in the devel package version 1.5.1, and release version 1.6.0. Please try updating your Bioconductor version.

Cheers!

**Comment by cathalgking** [comment]
this works now. Thanks.
