### ISSUE TITLE
Subset image in XY dimensions

### ISSUE THREAD

**Issue by MichelV2** [aoles/RBioFormats#5]
Hello,

I was digging in the code but I can't find a way to read a subset of an image in the X and Y dimensions.  I think this is possible with bioformats java library, would this be possible with the current version of RBioFormats? Or would there be a way to add this feature without recompiling the java code?

Thank you

**Comment by aoles** [comment]
Hi,
thank you for your feedback! The current version of RBioFormats allows only subsetting of color channels, z-stack and time frames. I think reading cropped images, i.e. ones subsetted in the X-Y dimensions, is not directly implemented in the BioFormats Java library, at least I'm not aware of such functionality (@openmicroscopy CC-ed). This could be done in post-processing, and I might add it in some future updates of the package.

However, this can be easily performed in R once the image is loaded: to crop an Image simply subset it as you would do with a regular array or matrix. For example, to cut out a 50x100 upper left corner use:

```{r}    
library("RBioFormats")

img <- read.image(system.file("images", "nuclei.tif", package = "EBImage"))
dim(img)
## [1] 510 510   4

img <- img[1:50, 1:100, ]
dim(img)
## [1]  50 100   4
```
Cheers,
Andrzej

**Comment by MichelV2** [comment]
Hello Andrzej! 

Thanks for your answer :) My question was mostly motivated by the need to process big images which cannot be directly loaded into memory. I believe there is an openBytes method in bioformats that accepts subseting in the XY dimensions and stores the output in a bytearray but I am not familiar at all with java so I might be wrong.

Cheers,
Michel

**Comment by aoles** [comment]
Now that I double checked it turns out that you're actually right, there is an `openBytes` methods allowing for cropping. I must have missed it in my my initial implementation, I'm sorry for the confusion.

Adding this functionality to RBioFormats will require both changes to R and Java code. I will look into this, so stay tuned.

Cheers,
Andrzej

**Comment by MichelV2** [comment]
Hi Andrzej, that's great, thank you. I actually tried myself but I am a total newbie in java and got lost with java code compilation.. I will stay tuned ;) Great package by the way.

Cheers,

Michel

**Comment by aoles** [comment]
Hi Michel,
I'm happy to inform you that I've added support for XY subsetting to `read.image()`. You can specify the cropping in the following way:

```{r}
f <- system.file("images", "nuclei.tif", package = "EBImage")
img <- read.image(f, subset = list(X = 1:50, Y = 1:100))
print(img, short=TRUE)

## AnnotatedImage 
##   colorMode    : Grayscale 
##   storage.mode : double 
##   dim          : 50 100 4 
##   dimorder     : X Y T 
##   frames.total : 4 
##   frames.render: 4 
## 
## metadata
##  $ coreMetadata  :List of 18
##  $ globalMetadata:List of 19
```
Cheers,
Andrzej

**Comment by MichelV2** [comment]
Hi Andrzej,

Many thanks for this update. Sorry for late answer, I just tested the function today. When the image is being red with X,Y subsets, the coordinates are kept constant over the resolution levels which leads to reading different parts of the image (or bugging when the coordinates do not exist in one particular level). Maybe it would make sense to read a constant part (ie non constant X and Y coordinates) of the image throughout the resolution levels? Also I get an error when I try to enter something in the "resolution" option: 
Error in mapply(function(s, r) { : argument is missing, with no default

Cheers,

Michel

**Comment by aoles** [comment]
Hi Michel,

thanks for your feedback. You're correct about the fact that fixed X-Y coordinates lead to cropping different parts of the frame across different resolutions. Keeping track of this would probably add a lot of complexity to the code with little benefit, so I won't be implementing it any time soon. There is a certain trade-off between simplicity of code and flexibility of user interface. Having said this, providing the suggested functionality is beyond my scope right now.

However, you were right about the error when specifying `resolution` to `read.image`. I've fixed this in my latest commit, so things should now work as expected. Don't hesitate to drop me a line in case you have any other questions or concerns.

Cheers,
Andrzej

**Comment by MichelV2** [comment]
I totally understand you point. The X,Y subsetting is a great feature for people working with pathology images, thanks a lot.

Michel

**Comment by aoles** [comment]
Thanks Michel! I will keep your feature request on my list of potential future improvements. Don't hesitate to contact me in case you have any further issues with the package.

Cheers,
Andrzej
