### ISSUE TITLE
Get number of frames in a TIFF video without reading into memory

### ISSUE THREAD

**Issue by beansprout88** [aoles/RBioFormats#6]
Hello!

Firstly, many thanks for a very useful package.

I was wondering, is it possible to get the dimensions of a TIFF image without opening the whole file into memory? I am analysing a very long video file that will not fit into memory, using the subset function to open each frame at a time with a loop. Is there a way I can do this with RBioFormats?

**Comment by beansprout88** [comment]
Found a solution, by first using read.metadata():

`number.of.frames <- read.metadata(file)@.Data[[1]]$sizeT`

**Comment by aoles** [comment]
Good call! The relevant metadata list can be also accessed with

```r
metadata <- read.metadata("filename")
number.of.frames <- coreMetadata(metadata)$sizeT
```
