### ISSUE TITLE
Using subset to open mages in a list one at a time

### ISSUE THREAD

**Issue by beansprout88** [aoles/RBioFormats#8]
Hello!

I am using the RBioFormats package to open `.lif` files, each of which contains multiple images and opens into a `Large AnnotatedImageList`.

I am having difficulty with some files due to their size, so would like to open each image from the `.lif` in turn and process them separately in a loop. Previously I have used the `subset` argument of `read.image()` to do this for video files by iterating through `t`, but this doesn't seem to be possible for opening multiple images in an archive. 

Is there a way that I can do this?

Thanks,
Daniel

**Comment by aoles** [comment]
Hi Daniel,
many thanks for your feedback. I'm happy to hear that you find `RBioFormats` useful in your project.

If the image opens as `AnnotatedImageList` then you could try subsetting individual image series with the `series` argument to `read.image`. Let me know whether this works for you.

**Comment by beansprout88** [comment]
Thanks Andrzej, I missed the series argument. That works perfectly. And thanks again for a very useful package!

**Comment by aoles** [comment]
Great, I'm glad this works for you!
